/**
 * Curated catalogue seed — the human half of the mock data.
 *
 * Each entry carries what a librarian decides (which shelf, which subject, what the book
 * is for, written in the reader's language) and a `query` that names the real edition.
 * `fetch-catalog.mjs` resolves that query against Open Library and fills in the facts
 * nobody should invent: exact title, real authors, publication year, ISBN-13, cover art.
 *
 * Bias is deliberately toward university textbooks — this is the reading list of a
 * natural-sciences faculty, not a bookshop's bestsellers.
 *
 * Fields
 *   id       stable slug; also the cover filename and the key in availability/loan mocks
 *   query    what to look up on Open Library
 *   expect   substring the resolved title must contain, so a bad match fails loudly
 *   subject  catalogue subject — must be one of the subjects librarian.ts knows
 *   shelf    shelf code — must exist in libraryMap.ts
 *   floor    floor the shelf sits on
 *   desc     Vietnamese one-liner shown on the book-info screen
 *   pin      optional: metadata to keep verbatim instead of fetching (Vietnamese textbooks,
 *            which Open Library indexes with mangled diacritics and no cover art)
 */

/** @typedef {{id:string,query:string,expect?:string,subject:string,shelf:string,floor:number,desc:string,type?:'book'|'journal'|'magazine',pin?:object}} SeedEntry */

/**
 * The four books the kiosk home screen greets a reader with ("Sách được mượn nhiều trong
 * học kỳ này") — a curation decision, not "whatever happens to be first in the list".
 *
 * One from each of four faculties, so the shelf on show reads as a whole library rather
 * than one department's reading list, and all four have real cover art. Their copy counts
 * are pinned in fetch-catalog.mjs to put a different availability state on each card:
 * a reader meets "Đã mượn hết" here, before walking, which is the persona's whole
 * complaint about the current system.
 */
export const SUGGESTED_IDS = [
  'cormen-algorithms',
  'stewart-calculus',
  'halliday-fundamentals-physics',
  'campbell-biology',
]

/** @type {SeedEntry[]} */
export const seed = [
  // ─────────────────────────────────────────────────────────────────────────
  // Giáo trình tiếng Việt. Open Library indexes these with stripped diacritics
  // ("So do", "tuỏ̂i thơ") and no cover art, so the metadata is pinned by hand from
  // the printed editions instead of fetched. These four lead the list because
  // `suggestedBooks` is the first four — the home screen greets a Vietnamese reader
  // with Vietnamese textbooks.
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'giai-tich-1',
    query: 'Giải tích 1',
    subject: 'Toán học',
    shelf: 'MA-101',
    floor: 1,
    desc: 'Giáo trình giải tích một biến dành cho sinh viên năm nhất khối kỹ thuật.',
    pin: {
      title: 'Giải tích 1',
      author: 'Nguyễn Đình Trí, Tạ Văn Đĩnh, Nguyễn Hồ Quỳnh',
      isbn: '9786040123456',
      year: 2018,
      language: 'vi',
    },
  },
  {
    id: 'vat-ly-dai-cuong',
    query: 'Vật lý đại cương',
    subject: 'Vật lý',
    shelf: 'PH-204',
    floor: 1,
    desc: 'Tổng quan cơ học, nhiệt học và điện từ học cho chương trình đại cương.',
    pin: {
      title: 'Vật lý đại cương',
      author: 'Lương Duyên Bình, Dư Trí Công, Nguyễn Hữu Hồ',
      isbn: '9786040234567',
      year: 2016,
      language: 'vi',
    },
  },
  {
    id: 'lap-trinh-cpp',
    query: 'Lập trình C++',
    subject: 'Công nghệ thông tin',
    shelf: 'CS-312',
    floor: 2,
    desc: 'Nhập môn lập trình hướng đối tượng với C++, kèm bài tập thực hành.',
    pin: {
      title: 'Lập trình C++',
      author: 'Phạm Văn Ất',
      isbn: '9786040345678',
      year: 2020,
      language: 'vi',
    },
  },
  {
    id: 'dai-so-tuyen-tinh',
    query: 'Đại số tuyến tính',
    subject: 'Toán học',
    shelf: 'MA-215',
    floor: 1,
    desc: 'Không gian vector, ma trận và ánh xạ tuyến tính, có ứng dụng thực tế.',
    pin: {
      title: 'Đại số tuyến tính',
      author: 'Nguyễn Hữu Việt Hưng',
      isbn: '9786040456789',
      year: 2019,
      language: 'vi',
    },
  },
  {
    id: 'xac-suat-thong-ke',
    query: 'Xác suất thống kê',
    subject: 'Toán học',
    shelf: 'MA-220',
    floor: 1,
    desc: 'Giáo trình xác suất và thống kê ứng dụng cho sinh viên khối khoa học tự nhiên.',
    pin: {
      title: 'Xác suất thống kê',
      author: 'Đinh Văn Gắng',
      isbn: '9786040567890',
      year: 2017,
      language: 'vi',
    },
  },
  {
    id: 'hoa-hoc-dai-cuong',
    query: 'Hóa học đại cương',
    subject: 'Hóa học',
    shelf: 'CH-110',
    floor: 1,
    desc: 'Cấu tạo nguyên tử, liên kết hóa học và nhiệt động hóa học cho năm nhất.',
    pin: {
      title: 'Hóa học đại cương',
      author: 'Nguyễn Đình Soa',
      isbn: '9786040678901',
      year: 2015,
      language: 'vi',
    },
  },
  {
    id: 'sinh-hoc-dai-cuong',
    query: 'Sinh học đại cương',
    subject: 'Sinh học',
    shelf: 'BI-105',
    floor: 1,
    desc: 'Nhập môn tế bào học, di truyền và tiến hóa theo chương trình đại cương.',
    pin: {
      title: 'Sinh học đại cương',
      author: 'Phạm Thành Hổ',
      isbn: '9786040789012',
      year: 2019,
      language: 'vi',
    },
  },
  {
    id: 'cau-truc-du-lieu-giai-thuat',
    query: 'Cấu trúc dữ liệu và giải thuật',
    subject: 'Công nghệ thông tin',
    shelf: 'CS-320',
    floor: 2,
    desc: 'Danh sách, cây, đồ thị và phân tích độ phức tạp, có mã nguồn minh họa.',
    pin: {
      title: 'Cấu trúc dữ liệu và giải thuật',
      author: 'Đỗ Xuân Lôi',
      isbn: '9786040890123',
      year: 2018,
      language: 'vi',
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // Toán học — Khu Toán đại cương & Toán ứng dụng, tầng 1
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'stewart-calculus',
    query: 'Calculus Early Transcendentals James Stewart',
    expect: 'Calculus',
    subject: 'Toán học',
    shelf: 'MA-102',
    floor: 1,
    desc: 'Giáo trình giải tích chuẩn quốc tế, nhiều bài tập ứng dụng kỹ thuật.',
  },
  {
    id: 'thomas-calculus',
    query: "Thomas' Calculus George B. Thomas",
    expect: 'Calculus',
    subject: 'Toán học',
    shelf: 'MA-103',
    floor: 1,
    desc: 'Giáo trình giải tích cổ điển, mạnh về hình học và trực giác.',
  },
  {
    id: 'strang-linear-algebra',
    query: 'Introduction to Linear Algebra Gilbert Strang',
    expect: 'Linear Algebra',
    subject: 'Toán học',
    shelf: 'MA-216',
    floor: 1,
    desc: 'Đại số tuyến tính theo lối trực quan của Gilbert Strang, gắn với MIT 18.06.',
  },
  {
    id: 'lay-linear-algebra',
    query: 'Linear Algebra and Its Applications David Lay',
    expect: 'Linear Algebra',
    subject: 'Toán học',
    shelf: 'MA-217',
    floor: 1,
    desc: 'Đại số tuyến tính với trọng tâm là ứng dụng và mô hình hóa.',
  },
  {
    id: 'rosen-discrete-math',
    query: 'Discrete Mathematics and Its Applications Kenneth Rosen',
    expect: 'Discrete Mathematics',
    subject: 'Toán học',
    shelf: 'MA-230',
    floor: 1,
    desc: 'Toán rời rạc: logic, tổ hợp, đồ thị — nền tảng cho ngành máy tính.',
  },
  {
    id: 'ross-probability',
    query: 'A First Course in Probability Sheldon Ross',
    expect: 'Probability',
    subject: 'Toán học',
    shelf: 'MA-221',
    floor: 1,
    desc: 'Nhập môn xác suất kinh điển, nhiều ví dụ và bài tập có lời giải.',
  },
  {
    id: 'ross-probability-models',
    query: 'Introduction to Probability Models Sheldon Ross',
    expect: 'Probability',
    subject: 'Toán học',
    shelf: 'MA-222',
    floor: 1,
    desc: 'Quá trình ngẫu nhiên, chuỗi Markov và lý thuyết hàng đợi.',
  },
  {
    id: 'rudin-analysis',
    query: 'Principles of Mathematical Analysis Walter Rudin',
    expect: 'Analysis',
    subject: 'Toán học',
    shelf: 'MA-240',
    floor: 1,
    desc: 'Giải tích thực chặt chẽ — giáo trình chuẩn cho sinh viên toán chuyên ngành.',
  },
  {
    id: 'boyce-differential-equations',
    query: 'Elementary Differential Equations and Boundary Value Problems Boyce',
    expect: 'Differential Equations',
    subject: 'Toán học',
    shelf: 'MA-241',
    floor: 1,
    desc: 'Phương trình vi phân thường và bài toán biên, có phần mô hình hóa.',
  },
  {
    id: 'kreyszig-engineering-math',
    query: 'Advanced Engineering Mathematics Erwin Kreyszig',
    expect: 'Engineering Mathematics',
    subject: 'Toán học',
    shelf: 'MA-242',
    floor: 1,
    desc: 'Toán kỹ thuật tổng hợp: vi phân, biến phức, giải tích số, thống kê.',
  },
  {
    id: 'burden-numerical-analysis',
    query: 'Numerical Analysis Richard Burden Faires',
    expect: 'Numerical Analysis',
    subject: 'Toán học',
    shelf: 'MA-243',
    floor: 1,
    desc: 'Giải tích số: sai số, nội suy, tích phân số và giải hệ tuyến tính.',
  },
  {
    id: 'dummit-abstract-algebra',
    query: 'Abstract Algebra Dummit Foote',
    expect: 'Abstract Algebra',
    subject: 'Toán học',
    shelf: 'MA-250',
    floor: 1,
    desc: 'Nhóm, vành, trường và lý thuyết Galois — giáo trình đại số trừu tượng chuẩn.',
  },
  {
    id: 'munkres-topology',
    query: 'Topology James Munkres',
    expect: 'Topology',
    subject: 'Toán học',
    shelf: 'MA-251',
    floor: 1,
    desc: 'Tôpô đại cương và nhập môn tôpô đại số.',
  },
  {
    id: 'concrete-mathematics',
    query: 'Concrete Mathematics Graham Knuth Patashnik',
    expect: 'Concrete Mathematics',
    subject: 'Toán học',
    shelf: 'MA-231',
    floor: 1,
    desc: 'Toán học nền cho khoa học máy tính: tổng, hệ số nhị thức, hàm sinh.',
  },
  {
    id: 'wasserman-all-of-statistics',
    query: 'All of Statistics Larry Wasserman',
    expect: 'Statistics',
    subject: 'Toán học',
    shelf: 'MA-223',
    floor: 1,
    desc: 'Thống kê hiện đại cô đọng, viết cho người làm khoa học dữ liệu.',
  },
  {
    id: 'rice-mathematical-statistics',
    query: 'Mathematical Statistics and Data Analysis John Rice',
    expect: 'Statistics',
    subject: 'Toán học',
    shelf: 'MA-224',
    floor: 1,
    desc: 'Thống kê toán học gắn chặt với phân tích dữ liệu thực nghiệm.',
  },

  // ─────────────────────────────────────────────────────────────────────────
  // Vật lý — Khu Vật lý, tầng 1
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'halliday-fundamentals-physics',
    query: 'Fundamentals of Physics Halliday Resnick Walker',
    expect: 'Physics',
    subject: 'Vật lý',
    shelf: 'PH-201',
    floor: 1,
    desc: 'Giáo trình vật lý đại cương quốc tế, bao trọn cơ – nhiệt – điện – quang.',
  },
  {
    id: 'young-university-physics',
    query: 'University Physics Young Freedman',
    expect: 'Physics',
    subject: 'Vật lý',
    shelf: 'PH-202',
    floor: 1,
    desc: 'Vật lý đại cương bậc đại học, chú trọng phương pháp giải bài toán.',
  },
  {
    id: 'serway-physics',
    query: 'Physics for Scientists and Engineers Serway Jewett',
    expect: 'Physics',
    subject: 'Vật lý',
    shelf: 'PH-203',
    floor: 1,
    desc: 'Vật lý cho sinh viên khoa học và kỹ thuật, nhiều bài tập phân mức.',
  },
  {
    id: 'griffiths-electrodynamics',
    query: 'Introduction to Electrodynamics David Griffiths',
    expect: 'Electrodynamics',
    subject: 'Vật lý',
    shelf: 'PH-210',
    floor: 1,
    desc: 'Điện động lực học cổ điển — giáo trình chuẩn cho chuyên ngành vật lý.',
  },
  {
    id: 'griffiths-quantum-mechanics',
    query: 'Introduction to Quantum Mechanics David Griffiths',
    expect: 'Quantum Mechanics',
    subject: 'Vật lý',
    shelf: 'PH-211',
    floor: 1,
    desc: 'Cơ học lượng tử nhập môn, trình bày sáng và nhiều bài tập.',
  },
  {
    id: 'goldstein-classical-mechanics',
    query: 'Classical Mechanics Herbert Goldstein',
    expect: 'Classical Mechanics',
    subject: 'Vật lý',
    shelf: 'PH-212',
    floor: 1,
    desc: 'Cơ học lý thuyết: hình thức Lagrange và Hamilton.',
  },
  {
    id: 'schroeder-thermal-physics',
    query: 'An Introduction to Thermal Physics Daniel Schroeder',
    expect: 'Thermal Physics',
    subject: 'Vật lý',
    shelf: 'PH-213',
    floor: 1,
    desc: 'Nhiệt động lực học và vật lý thống kê, viết dễ tiếp cận.',
  },
  {
    id: 'kittel-solid-state',
    query: 'Introduction to Solid State Physics Charles Kittel',
    expect: 'Solid State',
    subject: 'Vật lý',
    shelf: 'PH-214',
    floor: 1,
    desc: 'Vật lý chất rắn: mạng tinh thể, dao động mạng, vùng năng lượng.',
  },
  {
    id: 'hecht-optics',
    query: 'Optics Eugene Hecht',
    expect: 'Optics',
    subject: 'Vật lý',
    shelf: 'PH-215',
    floor: 1,
    desc: 'Quang học sóng, giao thoa, nhiễu xạ và quang học hiện đại.',
  },
  {
    id: 'feynman-lectures',
    query: 'The Feynman Lectures on Physics Richard Feynman',
    expect: 'Feynman',
    subject: 'Vật lý',
    shelf: 'PH-220',
    floor: 1,
    desc: 'Bộ bài giảng vật lý kinh điển của Richard Feynman tại Caltech.',
  },
  {
    id: 'beiser-modern-physics',
    query: 'Concepts of Modern Physics Arthur Beiser',
    expect: 'Modern Physics',
    subject: 'Vật lý',
    shelf: 'PH-216',
    floor: 1,
    desc: 'Vật lý hiện đại: thuyết tương đối hẹp, lượng tử, hạt nhân.',
  },
  {
    id: 'taylor-error-analysis',
    query: 'An Introduction to Error Analysis John Taylor',
    expect: 'Error Analysis',
    subject: 'Vật lý',
    shelf: 'PH-217',
    floor: 1,
    desc: 'Xử lý sai số trong đo đạc thực nghiệm — sách gối đầu của phòng thí nghiệm.',
  },

  // ─────────────────────────────────────────────────────────────────────────
  // Hóa học — Khu Hóa học, tầng 1
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'brown-central-science',
    query: 'Chemistry The Central Science Brown LeMay',
    expect: 'Chemistry',
    subject: 'Hóa học',
    shelf: 'CH-101',
    floor: 1,
    desc: 'Hóa đại cương quốc tế, liên kết chặt lý thuyết với hiện tượng thực tế.',
  },
  {
    id: 'atkins-physical-chemistry',
    query: 'Atkins Physical Chemistry Peter Atkins',
    expect: 'Physical Chemistry',
    subject: 'Hóa học',
    shelf: 'CH-120',
    floor: 1,
    desc: 'Hóa lý: nhiệt động, động hóa học, cơ lượng tử phân tử.',
  },
  {
    id: 'clayden-organic-chemistry',
    query: 'Organic Chemistry Clayden Greeves Warren',
    expect: 'Organic Chemistry',
    subject: 'Hóa học',
    shelf: 'CH-130',
    floor: 1,
    desc: 'Hóa hữu cơ hiện đại, giải thích theo cơ chế phản ứng thay vì học thuộc.',
  },
  {
    id: 'mcmurry-organic-chemistry',
    query: 'Organic Chemistry John McMurry',
    expect: 'Organic Chemistry',
    subject: 'Hóa học',
    shelf: 'CH-131',
    floor: 1,
    desc: 'Hóa hữu cơ trình bày theo nhóm chức, nhiều bài tập cơ chế.',
  },
  {
    id: 'shriver-inorganic-chemistry',
    query: 'Inorganic Chemistry Shriver Atkins',
    expect: 'Inorganic Chemistry',
    subject: 'Hóa học',
    shelf: 'CH-140',
    floor: 1,
    desc: 'Hóa vô cơ: cấu trúc, đối xứng, phức chất và hóa học nguyên tố.',
  },
  {
    id: 'harris-quantitative-analysis',
    query: 'Quantitative Chemical Analysis Daniel Harris',
    expect: 'Quantitative Chemical Analysis',
    subject: 'Hóa học',
    shelf: 'CH-150',
    floor: 1,
    desc: 'Hóa phân tích định lượng, chuẩn độ và xử lý số liệu phòng thí nghiệm.',
  },
  {
    id: 'skoog-instrumental-analysis',
    query: 'Principles of Instrumental Analysis Skoog Holler',
    expect: 'Instrumental Analysis',
    subject: 'Hóa học',
    shelf: 'CH-151',
    floor: 1,
    desc: 'Phân tích công cụ: phổ, sắc ký, điện hóa và kỹ thuật đo hiện đại.',
  },
  {
    id: 'lehninger-biochemistry',
    query: 'Lehninger Principles of Biochemistry Nelson Cox',
    expect: 'Biochemistry',
    subject: 'Hóa học',
    shelf: 'CH-160',
    floor: 1,
    desc: 'Hóa sinh: cấu trúc đại phân tử, chuyển hóa và điều hòa trao đổi chất.',
  },
  {
    id: 'stryer-biochemistry',
    query: 'Biochemistry Berg Tymoczko Stryer',
    expect: 'Biochemistry',
    subject: 'Hóa học',
    shelf: 'CH-161',
    floor: 1,
    desc: 'Hóa sinh trình bày theo hướng cấu trúc – chức năng, nhiều hình minh họa.',
  },
  {
    id: 'pauling-general-chemistry',
    query: 'General Chemistry Linus Pauling',
    expect: 'General chemistry',
    subject: 'Hóa học',
    shelf: 'CH-102',
    floor: 1,
    desc: 'Hóa đại cương của Linus Pauling — kinh điển, giải thích từ cấu trúc nguyên tử.',
  },

  // ─────────────────────────────────────────────────────────────────────────
  // Sinh học — Khu Sinh học, tầng 1
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'alberts-molecular-biology-cell',
    query: 'Molecular Biology of the Cell Bruce Alberts',
    expect: 'Molecular Biology of the Cell',
    subject: 'Sinh học',
    shelf: 'BI-110',
    floor: 1,
    desc: 'Sinh học phân tử tế bào — giáo trình tham chiếu của toàn ngành.',
  },
  {
    id: 'campbell-biology',
    query: 'Campbell Biology Neil Campbell Reece',
    expect: 'Biology',
    subject: 'Sinh học',
    shelf: 'BI-106',
    floor: 1,
    desc: 'Sinh học đại cương quốc tế, bao quát từ phân tử tới hệ sinh thái.',
  },
  {
    id: 'alberts-essential-cell-biology',
    query: 'Essential Cell Biology Alberts',
    expect: 'Essential Cell Biology',
    subject: 'Sinh học',
    shelf: 'BI-111',
    floor: 1,
    desc: 'Bản rút gọn của Molecular Biology of the Cell, hợp cho sinh viên năm hai.',
  },
  {
    id: 'watson-molecular-biology-gene',
    query: 'Molecular Biology of the Gene James Watson',
    expect: 'Molecular Biology of the Gene',
    subject: 'Sinh học',
    shelf: 'BI-120',
    floor: 1,
    desc: 'Cơ chế phân tử của di truyền: sao chép, phiên mã, dịch mã và điều hòa gen.',
  },
  {
    id: 'griffiths-genetic-analysis',
    query: 'An Introduction to Genetic Analysis Griffiths',
    expect: 'Genetic Analysis',
    subject: 'Sinh học',
    shelf: 'BI-121',
    floor: 1,
    desc: 'Di truyền học tiếp cận qua phân tích thí nghiệm và bài toán lai.',
  },
  {
    id: 'tortora-microbiology',
    query: 'Microbiology An Introduction Tortora Funke Case',
    expect: 'Microbiology',
    subject: 'Sinh học',
    shelf: 'BI-130',
    floor: 1,
    desc: 'Vi sinh vật học nhập môn, gắn với y học và công nghệ thực phẩm.',
  },
  {
    id: 'madigan-brock-microbiology',
    query: 'Brock Biology of Microorganisms Madigan',
    expect: 'Microorganisms',
    subject: 'Sinh học',
    shelf: 'BI-131',
    floor: 1,
    desc: 'Sinh học vi sinh vật chuyên sâu: trao đổi chất, sinh thái và đa dạng.',
  },
  {
    id: 'janeway-immunobiology',
    query: "Janeway's Immunobiology Murphy Weaver",
    expect: 'Immunobiology',
    subject: 'Sinh học',
    shelf: 'BI-140',
    floor: 1,
    desc: 'Miễn dịch học: đáp ứng bẩm sinh, thích ứng và bệnh lý miễn dịch.',
  },
  {
    id: 'begon-ecology',
    query: 'Ecology From Individuals to Ecosystems Begon Townsend Harper',
    expect: 'Ecology',
    subject: 'Sinh học',
    shelf: 'BI-150',
    floor: 1,
    desc: 'Sinh thái học từ cá thể tới hệ sinh thái, nhiều nghiên cứu điển hình.',
  },
  {
    id: 'pevsner-bioinformatics',
    query: 'Bioinformatics and Functional Genomics Jonathan Pevsner',
    expect: 'Bioinformatics',
    subject: 'Sinh học',
    shelf: 'BI-160',
    floor: 1,
    desc: 'Tin sinh học: so sánh trình tự, hệ gen chức năng và công cụ phân tích.',
  },

  // ─────────────────────────────────────────────────────────────────────────
  // Công nghệ thông tin — Khu Công nghệ thông tin, tầng 2
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'cormen-algorithms',
    query: 'Introduction to Algorithms Cormen Leiserson Rivest Stein',
    expect: 'Algorithms',
    subject: 'Công nghệ thông tin',
    shelf: 'CS-301',
    floor: 2,
    desc: 'Giáo trình thuật toán chuẩn mực, phân tích chặt chẽ kèm mã giả.',
  },
  {
    id: 'sedgewick-algorithms',
    query: 'Algorithms Robert Sedgewick Kevin Wayne',
    expect: 'Algorithms',
    subject: 'Công nghệ thông tin',
    shelf: 'CS-302',
    floor: 2,
    desc: 'Thuật toán và cấu trúc dữ liệu cài đặt bằng Java, thiên về thực hành.',
  },
  {
    id: 'skiena-algorithm-design',
    query: 'The Algorithm Design Manual Steven Skiena',
    expect: 'Algorithm Design',
    subject: 'Công nghệ thông tin',
    shelf: 'CS-303',
    floor: 2,
    desc: 'Cẩm nang chọn và thiết kế thuật toán cho bài toán thực tế.',
  },
  {
    id: 'sipser-theory-computation',
    query: 'Introduction to the Theory of Computation Michael Sipser',
    expect: 'Theory of Computation',
    subject: 'Công nghệ thông tin',
    shelf: 'CS-304',
    floor: 2,
    desc: 'Lý thuyết tính toán: ôtômát, tính khả quyết và độ phức tạp.',
  },
  {
    id: 'kernighan-c-programming',
    query: 'The C Programming Language Kernighan Ritchie',
    expect: 'C Programming Language',
    subject: 'Công nghệ thông tin',
    shelf: 'CS-310',
    floor: 2,
    desc: 'Sách gốc về ngôn ngữ C, ngắn gọn và chính xác tới từng câu.',
  },
  {
    id: 'stroustrup-cpp',
    query: 'The C++ Programming Language Bjarne Stroustrup',
    expect: 'C++',
    subject: 'Công nghệ thông tin',
    shelf: 'CS-311',
    floor: 2,
    desc: 'Tài liệu tham chiếu về C++ do chính tác giả ngôn ngữ viết.',
  },
  {
    id: 'abelson-sicp',
    query: 'Structure and Interpretation of Computer Programs Abelson Sussman',
    expect: 'Computer Programs',
    subject: 'Công nghệ thông tin',
    shelf: 'CS-313',
    floor: 2,
    desc: 'Nền tảng tư duy lập trình qua trừu tượng hóa, giáo trình kinh điển của MIT.',
  },
  {
    id: 'bloch-effective-java',
    query: 'Effective Java Joshua Bloch',
    expect: 'Effective Java',
    subject: 'Công nghệ thông tin',
    shelf: 'CS-314',
    floor: 2,
    desc: '78 nguyên tắc viết Java đúng và bền, dành cho người đã biết cú pháp.',
  },
  {
    id: 'ramalho-fluent-python',
    query: 'Fluent Python Luciano Ramalho',
    expect: 'Fluent Python',
    subject: 'Công nghệ thông tin',
    shelf: 'CS-315',
    floor: 2,
    desc: 'Khai thác Python đúng phong cách ngôn ngữ: data model, iterator, coroutine.',
  },
  {
    id: 'matthes-python-crash-course',
    query: 'Python Crash Course Eric Matthes',
    expect: 'Python',
    subject: 'Công nghệ thông tin',
    shelf: 'CS-316',
    floor: 2,
    desc: 'Nhập môn Python theo dự án, phù hợp người mới bắt đầu lập trình.',
  },
  {
    id: 'haverbeke-eloquent-javascript',
    query: 'Eloquent JavaScript Marijn Haverbeke',
    expect: 'JavaScript',
    subject: 'Công nghệ thông tin',
    shelf: 'CS-317',
    floor: 2,
    desc: 'JavaScript từ cơ bản tới lập trình hàm và ứng dụng web.',
  },
  {
    id: 'silberschatz-operating-systems',
    query: 'Operating System Concepts Silberschatz Galvin Gagne',
    expect: 'Operating System',
    subject: 'Công nghệ thông tin',
    shelf: 'CS-330',
    floor: 2,
    desc: 'Hệ điều hành: tiến trình, đồng bộ, bộ nhớ ảo và hệ thống tệp.',
  },
  {
    id: 'tanenbaum-modern-operating-systems',
    query: 'Modern Operating Systems Andrew Tanenbaum',
    expect: 'Operating Systems',
    subject: 'Công nghệ thông tin',
    shelf: 'CS-331',
    floor: 2,
    desc: 'Hệ điều hành hiện đại, nhiều tình huống thiết kế thực tế.',
  },
  {
    id: 'tanenbaum-computer-networks',
    query: 'Computer Networks Andrew Tanenbaum',
    expect: 'Computer Networks',
    subject: 'Công nghệ thông tin',
    shelf: 'CS-340',
    floor: 2,
    desc: 'Mạng máy tính theo mô hình phân tầng, từ vật lý tới ứng dụng.',
  },
  {
    id: 'kurose-computer-networking',
    query: 'Computer Networking Top-Down Approach',
    expect: 'Computer Networking',
    subject: 'Công nghệ thông tin',
    shelf: 'CS-341',
    floor: 2,
    desc: 'Mạng máy tính tiếp cận từ tầng ứng dụng xuống, dễ vào cho sinh viên.',
  },
  {
    id: 'silberschatz-database-concepts',
    query: 'Database System Concepts Silberschatz Korth Sudarshan',
    expect: 'Database',
    subject: 'Công nghệ thông tin',
    shelf: 'CS-350',
    floor: 2,
    desc: 'Cơ sở dữ liệu: mô hình quan hệ, SQL, giao tác và tối ưu truy vấn.',
  },
  {
    id: 'kleppmann-data-intensive',
    query: 'Designing Data-Intensive Applications',
    expect: 'Data-Intensive',
    subject: 'Công nghệ thông tin',
    shelf: 'CS-351',
    floor: 2,
    desc: 'Hệ thống dữ liệu phân tán: nhân bản, phân mảnh, nhất quán và xử lý luồng.',
  },
  {
    id: 'patterson-computer-organization',
    query: 'Computer Organization and Design Patterson Hennessy',
    expect: 'Computer Organization',
    subject: 'Công nghệ thông tin',
    shelf: 'CS-360',
    floor: 2,
    desc: 'Kiến trúc máy tính từ tập lệnh tới pipeline và phân cấp bộ nhớ.',
  },
  {
    id: 'bryant-csapp',
    query: "Computer Systems Programmer's Perspective",
    expect: 'Computer Systems',
    subject: 'Công nghệ thông tin',
    shelf: 'CS-361',
    floor: 2,
    desc: 'Hệ thống máy tính nhìn từ góc người lập trình: biểu diễn dữ liệu tới liên kết.',
  },
  {
    id: 'aho-compilers',
    query: 'Compilers Principles Techniques and Tools Aho Lam Sethi Ullman',
    expect: 'Compilers',
    subject: 'Công nghệ thông tin',
    shelf: 'CS-370',
    floor: 2,
    desc: 'Trình biên dịch: phân tích từ vựng, cú pháp, sinh mã và tối ưu.',
  },
  {
    id: 'gamma-design-patterns',
    query: 'Design Patterns Gamma Helm',
    expect: 'Design Patterns',
    subject: 'Công nghệ thông tin',
    shelf: 'CS-380',
    floor: 2,
    desc: '23 mẫu thiết kế hướng đối tượng — sách gốc của nhóm Gang of Four.',
  },
  {
    id: 'martin-clean-code',
    query: 'Clean Code Robert C. Martin',
    expect: 'Clean Code',
    subject: 'Công nghệ thông tin',
    shelf: 'CS-381',
    floor: 2,
    desc: 'Nguyên tắc viết mã dễ đọc, dễ sửa, kèm ví dụ tái cấu trúc thực tế.',
  },
  {
    id: 'fowler-refactoring',
    query: 'Refactoring Improving the Design of Existing Code Martin Fowler',
    expect: 'Refactoring',
    subject: 'Công nghệ thông tin',
    shelf: 'CS-382',
    floor: 2,
    desc: 'Danh mục kỹ thuật tái cấu trúc mã có kiểm thử bảo vệ.',
  },
  {
    id: 'hunt-pragmatic-programmer',
    query: 'The Pragmatic Programmer Andrew Hunt David Thomas',
    expect: 'Pragmatic Programmer',
    subject: 'Công nghệ thông tin',
    shelf: 'CS-383',
    floor: 2,
    desc: 'Thói quen nghề nghiệp của lập trình viên: tự động hóa, gỡ lỗi, giao tiếp.',
  },
  {
    id: 'mcconnell-code-complete',
    query: 'Code Complete Steve McConnell',
    expect: 'Code Complete',
    subject: 'Công nghệ thông tin',
    shelf: 'CS-384',
    floor: 2,
    desc: 'Cẩm nang xây dựng phần mềm ở cấp độ mã nguồn, dày dặn và thực dụng.',
  },
  {
    id: 'sommerville-software-engineering',
    query: 'Software Engineering Ian Sommerville',
    expect: 'Software Engineering',
    subject: 'Công nghệ thông tin',
    shelf: 'CS-385',
    floor: 2,
    desc: 'Công nghệ phần mềm: quy trình, yêu cầu, kiến trúc và kiểm thử.',
  },
  {
    id: 'stallings-cryptography',
    query: 'Cryptography and Network Security William Stallings',
    expect: 'Cryptography',
    subject: 'Công nghệ thông tin',
    shelf: 'CS-390',
    floor: 2,
    desc: 'Mật mã học và an toàn mạng: khóa đối xứng, khóa công khai, giao thức.',
  },
  {
    id: 'hughes-computer-graphics',
    query: 'Computer Graphics Principles and Practice Hughes Foley',
    expect: 'Computer Graphics',
    subject: 'Công nghệ thông tin',
    shelf: 'CS-391',
    floor: 2,
    desc: 'Đồ họa máy tính: biến đổi hình học, dựng hình, chiếu sáng và kết cấu.',
  },

  // ─────────────────────────────────────────────────────────────────────────
  // Machine Learning — Khu Machine Learning, tầng 2
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'statistical-learning',
    query: 'An Introduction to Statistical Learning James Witten Hastie Tibshirani',
    expect: 'Statistical Learning',
    subject: 'Machine Learning',
    shelf: 'A3',
    floor: 2,
    desc: 'Nhập môn học thống kê kèm bài thực hành R — sách vào ngành phổ biến nhất.',
  },
  {
    id: 'hands-on-ml',
    query: 'Hands-On Machine Learning Scikit-Learn',
    expect: 'Machine Learning',
    subject: 'Machine Learning',
    shelf: 'A4',
    floor: 2,
    desc: 'Thực hành học máy với Scikit-Learn, Keras và TensorFlow.',
  },
  {
    id: 'pattern-recognition',
    query: 'Pattern Recognition and Machine Learning Christopher Bishop',
    expect: 'Pattern Recognition',
    subject: 'Machine Learning',
    shelf: 'A5',
    floor: 2,
    desc: 'Giáo trình kinh điển về nhận dạng mẫu và mô hình xác suất trong học máy.',
  },
  {
    id: 'mathematics-for-ml',
    query: 'Mathematics for Machine Learning Deisenroth Faisal Ong',
    expect: 'Mathematics for Machine Learning',
    subject: 'Machine Learning',
    shelf: 'B2',
    floor: 2,
    desc: 'Nền tảng đại số tuyến tính, giải tích và xác suất cần cho học máy.',
  },
  {
    id: 'goodfellow-deep-learning',
    query: 'Deep Learning Ian Goodfellow Yoshua Bengio Aaron Courville',
    expect: 'Deep Learning',
    subject: 'Machine Learning',
    shelf: 'A6',
    floor: 2,
    desc: 'Giáo trình học sâu chuẩn: mạng nơ-ron, tối ưu và mô hình sinh.',
  },
  {
    id: 'hastie-elements-statistical-learning',
    query: 'The Elements of Statistical Learning Hastie Tibshirani Friedman',
    expect: 'Statistical Learning',
    subject: 'Machine Learning',
    shelf: 'A7',
    floor: 2,
    desc: 'Bản nâng cao của học thống kê, nặng toán và bao quát rộng.',
  },
  {
    id: 'murphy-probabilistic-ml',
    query: 'Machine Learning A Probabilistic Perspective Kevin Murphy',
    expect: 'Machine Learning',
    subject: 'Machine Learning',
    shelf: 'A8',
    floor: 2,
    desc: 'Học máy nhìn hoàn toàn qua lăng kính xác suất, tra cứu rất đầy đủ.',
  },
  {
    id: 'sutton-reinforcement-learning',
    query: 'Reinforcement Learning An Introduction Sutton Barto',
    expect: 'Reinforcement Learning',
    subject: 'Machine Learning',
    shelf: 'B1',
    floor: 2,
    desc: 'Học tăng cường từ bài toán bandit tới phương pháp gradient chính sách.',
  },
  {
    id: 'jurafsky-speech-language',
    query: 'Speech and Language Processing Jurafsky Martin',
    expect: 'Speech and Language Processing',
    subject: 'Machine Learning',
    shelf: 'B3',
    floor: 2,
    desc: 'Xử lý ngôn ngữ tự nhiên: từ n-gram tới mô hình transformer.',
  },
  {
    id: 'chollet-deep-learning-python',
    query: 'Deep Learning with Python François Chollet',
    expect: 'Deep Learning',
    subject: 'Machine Learning',
    shelf: 'B4',
    floor: 2,
    desc: 'Học sâu thực hành với Keras, do chính tác giả thư viện viết.',
  },
  {
    id: 'mackay-information-theory',
    query: 'Information Theory Inference and Learning Algorithms David MacKay',
    expect: 'Information Theory',
    subject: 'Machine Learning',
    shelf: 'B5',
    floor: 2,
    desc: 'Lý thuyết thông tin, suy diễn Bayes và mã sửa lỗi trong một mạch trình bày.',
  },
  {
    id: 'mckinney-python-data-analysis',
    query: 'Python for Data Analysis Wes McKinney',
    expect: 'Data Analysis',
    subject: 'Machine Learning',
    shelf: 'B6',
    floor: 2,
    desc: 'Phân tích dữ liệu với pandas và NumPy, viết bởi tác giả pandas.',
  },
  {
    id: 'grus-data-science-scratch',
    query: 'Data Science from Scratch Joel Grus',
    expect: 'Data Science',
    subject: 'Machine Learning',
    shelf: 'B7',
    floor: 2,
    desc: 'Tự cài đặt các thuật toán khoa học dữ liệu bằng Python thuần để hiểu gốc.',
  },
  {
    id: 'szeliski-computer-vision',
    query: 'Computer Vision Algorithms and Applications Richard Szeliski',
    expect: 'Computer Vision',
    subject: 'Machine Learning',
    shelf: 'B8',
    floor: 2,
    desc: 'Thị giác máy tính: đặc trưng ảnh, hình học đa góc nhìn, nhận dạng.',
  },
  {
    id: 'russell-norvig-aima',
    query: 'Artificial Intelligence A Modern Approach Russell Norvig',
    expect: 'Artificial Intelligence',
    subject: 'Machine Learning',
    shelf: 'A9',
    floor: 2,
    desc: 'Trí tuệ nhân tạo toàn cảnh: tìm kiếm, suy diễn, học máy và tác tử.',
  },

  // ─────────────────────────────────────────────────────────────────────────
  // Điện tử – Viễn thông — Khu Điện tử, tầng 2
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'sedra-microelectronic-circuits',
    query: 'Microelectronic Circuits Sedra Smith',
    expect: 'Microelectronic Circuits',
    subject: 'Điện tử – Viễn thông',
    shelf: 'EE-201',
    floor: 2,
    desc: 'Mạch vi điện tử: transistor, khuếch đại và mạch tích hợp tương tự.',
  },
  {
    id: 'horowitz-art-of-electronics',
    query: 'The Art of Electronics Horowitz Hill',
    expect: 'Art of Electronics',
    subject: 'Điện tử – Viễn thông',
    shelf: 'EE-202',
    floor: 2,
    desc: 'Điện tử thực hành kinh điển, thiên về thiết kế mạch chạy được thật.',
  },
  {
    id: 'alexander-electric-circuits',
    query: 'Fundamentals of Electric Circuits Alexander Sadiku',
    expect: 'Electric Circuits',
    subject: 'Điện tử – Viễn thông',
    shelf: 'EE-203',
    floor: 2,
    desc: 'Lý thuyết mạch điện: một chiều, xoay chiều, đáp ứng quá độ.',
  },
  {
    id: 'oppenheim-signals-systems',
    query: 'Signals and Systems Oppenheim Willsky',
    expect: 'Signals and Systems',
    subject: 'Điện tử – Viễn thông',
    shelf: 'EE-210',
    floor: 2,
    desc: 'Tín hiệu và hệ thống: chập, Fourier, Laplace và biến đổi Z.',
  },
  {
    id: 'oppenheim-discrete-signal-processing',
    query: 'Discrete-Time Signal Processing',
    expect: 'Signal Processing',
    subject: 'Điện tử – Viễn thông',
    shelf: 'EE-211',
    floor: 2,
    desc: 'Xử lý tín hiệu số: thiết kế bộ lọc, DFT và phân tích phổ.',
  },
  {
    id: 'mano-digital-design',
    query: 'Digital Design M. Morris Mano',
    expect: 'Digital Design',
    subject: 'Điện tử – Viễn thông',
    shelf: 'EE-220',
    floor: 2,
    desc: 'Thiết kế số: đại số Boole, mạch tổ hợp, tuần tự và Verilog.',
  },

  // ─────────────────────────────────────────────────────────────────────────
  // Khoa học Trái Đất & Môi trường — tầng 3
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'grotzinger-understanding-earth',
    query: 'Understanding Earth Grotzinger Jordan',
    expect: 'Understanding Earth',
    subject: 'Khoa học môi trường',
    shelf: 'ES-101',
    floor: 3,
    desc: 'Địa chất đại cương: kiến tạo mảng, đá, khoáng vật và chu trình địa chất.',
  },
  {
    id: 'miller-living-in-environment',
    query: 'Living in the Environment G. Tyler Miller',
    expect: 'Environment',
    subject: 'Khoa học môi trường',
    shelf: 'ES-110',
    floor: 3,
    desc: 'Khoa học môi trường: tài nguyên, ô nhiễm và phát triển bền vững.',
  },
  {
    id: 'ahrens-meteorology-today',
    query: 'Meteorology Today Ahrens',
    expect: 'Meteorology',
    subject: 'Khoa học môi trường',
    shelf: 'ES-120',
    floor: 3,
    desc: 'Khí tượng học: khí quyển, thời tiết và biến đổi khí hậu.',
  },
  {
    id: 'vanloon-environmental-chemistry',
    query: 'Environmental Chemistry Baird',
    expect: 'Environmental Chemistry',
    subject: 'Khoa học môi trường',
    shelf: 'ES-130',
    floor: 3,
    desc: 'Hóa học môi trường: khí quyển, thủy quyển, thổ nhưỡng và chất ô nhiễm.',
  },
  {
    id: 'trenberth-climate-system',
    query: 'Global Warming The Complete Briefing John Houghton',
    expect: 'Global Warming',
    subject: 'Khoa học môi trường',
    shelf: 'ES-121',
    floor: 3,
    desc: 'Tổng quan khoa học về nóng lên toàn cầu và ứng phó chính sách.',
  },

  // ─────────────────────────────────────────────────────────────────────────
  // Báo khoa học & Tạp chí — tầng 3. Metadata pinned: these are periodicals,
  // not editions Open Library resolves to a single cover.
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'jmlr-deep-learning',
    query: 'Journal of Machine Learning Research',
    subject: 'Machine Learning',
    shelf: 'J1',
    floor: 3,
    type: 'journal',
    desc: 'Tuyển tập bài báo về tiến bộ gần đây trong học sâu.',
    pin: {
      title: 'Deep Learning Advances (JMLR tuyển tập)',
      author: 'Journal of Machine Learning Research',
      isbn: '9772153001007',
      year: 2024,
      language: 'en',
    },
  },
  {
    id: 'nature-machine-intelligence',
    query: 'Nature Machine Intelligence',
    subject: 'Machine Learning',
    shelf: 'J2',
    floor: 3,
    type: 'journal',
    desc: 'Tạp chí khoa học về trí tuệ máy và ứng dụng liên ngành.',
    pin: {
      title: 'Nature Machine Intelligence (số mới nhất)',
      author: 'Nature Publishing Group',
      isbn: '9772522583003',
      year: 2025,
      language: 'en',
    },
  },
  {
    id: 'tia-sang-ai',
    query: 'Tạp chí Tia Sáng',
    subject: 'Machine Learning',
    shelf: 'M1',
    floor: 3,
    type: 'magazine',
    desc: 'Chuyên đề phổ thông về trí tuệ nhân tạo và tác động xã hội.',
    pin: {
      title: 'Tia Sáng — chuyên đề Trí tuệ nhân tạo',
      author: 'Tạp chí Tia Sáng',
      isbn: '9771859123004',
      year: 2024,
      language: 'vi',
    },
  },
  {
    id: 'nature-journal',
    query: 'Nature',
    subject: 'Sinh học',
    shelf: 'J3',
    floor: 3,
    type: 'journal',
    desc: 'Tạp chí khoa học đa ngành, số lưu hành trong phòng đọc.',
    pin: {
      title: 'Nature (số lưu hành)',
      author: 'Nature Publishing Group',
      isbn: '9770028083009',
      year: 2025,
      language: 'en',
    },
  },
  {
    id: 'science-journal',
    query: 'Science',
    subject: 'Vật lý',
    shelf: 'J4',
    floor: 3,
    type: 'journal',
    desc: 'Tuần san khoa học của AAAS, đọc tại chỗ khu Báo & Tạp chí.',
    pin: {
      title: 'Science (số lưu hành)',
      author: 'American Association for the Advancement of Science',
      isbn: '9770036807003',
      year: 2025,
      language: 'en',
    },
  },
  {
    id: 'tap-chi-toan-hoc-tuoi-tre',
    query: 'Toán học và Tuổi trẻ',
    subject: 'Toán học',
    shelf: 'M2',
    floor: 3,
    type: 'magazine',
    desc: 'Tạp chí toán phổ thông và đại cương, chuyên mục đề và lời giải.',
    pin: {
      title: 'Toán học và Tuổi trẻ',
      author: 'Nhà xuất bản Giáo dục Việt Nam',
      isbn: '9771859234005',
      year: 2025,
      language: 'vi',
    },
  },
]
