/**
 * The database, as Kysely sees it — one interface per table, snake_case columns.
 *
 * Two properties of this schema are deliberate and load-bearing for the dual-database
 * requirement:
 *
 *   1. **No auto-increment anywhere.** Every primary key is a string the application
 *      generates. Postgres spells identity columns `serial`/`generated as identity` and
 *      SQL Server spells them `int identity(1,1)`, and getting the new value back needs
 *      `RETURNING` on one and `OUTPUT INSERTED` on the other. Sidestepping identity
 *      columns removes both differences at once — and the domain already had natural
 *      keys: a book id is a slug, a slip id is a printed number.
 *
 *   2. **Dates are ISO strings, not `Date`.** The columns are real `date` columns, but
 *      both drivers are configured to hand back `'YYYY-MM-DD'` — see server/db/dates.ts
 *      for why (the two drivers disagree about which midnight a bare date means). The
 *      whole application already treats dates as sortable strings.
 */

export interface BooksTable {
  id: string
  title: string
  isbn: string
  author: string
  subject: string
  type: string
  cover_url: string | null
  spine: number
  description: string
  shelf_code: string
  floor: number
  year: number
  language: string
  /**
   * Title + author + subject, lowercased with the diacritics folded off, written by the
   * seeder with `buildSearchText` from @/shared/text.
   *
   * This column is how the search stays identical on both engines. Matching accent- and
   * case-insensitively is where the two databases diverge hardest — Postgres wants the
   * `unaccent` extension and `ILIKE`, SQL Server wants an accent-insensitive collation on
   * the column — and both are configuration a marker would have to reproduce to run this
   * project. Folding the text once, at seed time, in the same TypeScript function the
   * browser used to use, turns the query into a plain `LIKE` that needs neither.
   */
  search_text: string
}

export interface ShelfLocationsTable {
  shelf_code: string
  floor: number
  zone: string
  aisle: number
  along_aisle: number
  distance_metres: number
}

/** `ShelfLocation.directions[]`, normalised — `step_no` preserves the walking order. */
export interface ShelfDirectionsTable {
  shelf_code: string
  step_no: number
  text: string
}

export interface AvailabilityTable {
  book_id: string
  status: string
  copies_total: number
  copies_available: number
  /** Display string in `dd/MM` ("Chờ trả: 25/11"), not an ISO date. See Availability. */
  due_back: string | null
}

export interface StudentsTable {
  card_code: string
  name: string
  student_id: string
  faculty: string
  expires_at: string
}

/**
 * A visit to the kiosk, not a book.
 *
 * A real table rather than something grouped out of `loans` at read time: two separate
 * visits on the same day would collapse into one slip if the grouping key were
 * borrowed_at + due_at, and the resulting slip would have no number of its own to show
 * the reader or encode in a QR code.
 */
export interface LoanSlipsTable {
  id: string
  card_code: string
  borrowed_at: string
  due_at: string
  created_at: string
}

export interface LoansTable {
  /** `${slip_id}::${book_id}` — generated by the app, so no identity column is needed. */
  id: string
  slip_id: string
  card_code: string
  book_id: string
  borrowed_at: string
  due_at: string
  returned_at: string | null
}

/** Exactly one row, `id = 1`. A settings record, modelled as a table with a fixed key. */
export interface LibraryStatusTable {
  id: number
  is_open: boolean
  opens_at: string
  closes_at: string
  titles_total: number
  titles_available: number
  support_phone: string
}

export interface DB {
  books: BooksTable
  shelf_locations: ShelfLocationsTable
  shelf_directions: ShelfDirectionsTable
  availability: AvailabilityTable
  students: StudentsTable
  loan_slips: LoanSlipsTable
  loans: LoansTable
  library_status: LibraryStatusTable
}
